### ISSUE TITLE
Updating Linux install instructions via Flatpak

### ISSUE THREAD

**Issue by MannyDiera** [okta/okta-cli#118]
Just wanted to point out the second step for installing via Flatpak requires the flathub remote name before the package name. 

Is it ok if I submit a PR?

From this:
`flatpak install com.okta.developer.CLI
`

To this:
`flatpak install flathub com.okta.developer.CLI
`

**Comment by mraible** [comment]
Thanks for pointing this out. Yes, please submit a PR.

**Comment by MannyDiera** [comment]
> Thanks for pointing this out. Yes, please submit a PR.

Thanks! Big fan of your work and thanks for building these awesome tools.
