### ISSUE TITLE
Semantic UI, jQuery and Vue webpack error

### ISSUE THREAD

**Issue by colby02184** [okta/okta-cli#159]
Semantic UI has a dependency on jQuery and I can't seem to get around the error below. I've tried importing jQuery in main.js and in the file where I need to use jQuery (for semantic UI's form validation). Any ideas how to fix it?

TypeError: jquery__WEBPACK_IMPORTED_MODULE_0___default(...)(...).form is not a function"

**Comment by bdemers** [comment]
Hey @colby02184!

Was this issue opened against the correct repo?  Did your run into a problem with one of our samples? Can you add more details on how we can reproduce the problem?

**Comment by colby02184** [comment]
Hey dbemers, 

Thanks for the response. Apologies if this is the incorrect repo. So I created a project with the okta cli and the command I used was okta start vue. The projected was created correctly and I was even able to log in to my okta org. The problem I have is with Semantic UI, for example when I add their jquery form validations to one of my components, webpack throws the error below. It does look like jquery is part of the sample project, however, I can't seem to get around the error, even after importing jquery directly on the component. 

TypeError: jquery__WEBPACK_IMPORTED_MODULE_0___default(...)(...).form is not a function"

You should be able to reproduce the issue by just dropping in one of Semantic UI's form and include some of their jquery validation code for the form. I went to https://semantic-ui.com/behaviors/form.html to grab that code. 

Thanks for your help!
