### ISSUE TITLE
`okta apps` shows disabled apps

### ISSUE THREAD

**Issue by mraible** [okta/okta-cli#270]
I was running an app today that kept giving me a 400 error. Using the CLI, I ran `okta apps` and made sure I had the correct client ID. Once I confirmed this was correct, I was quite puzzled. Then, I logged into the Okta Admin Console and discovered the app wasn't listed. I checked my Okta org URL because I was super confused on why it wouldn't be there. Then, I realized it was disabled. Once I enabled it again, everything worked. I imagine other developers might run into this issue.

**Comment by bdemers** [comment]
That's a good point 🤔 
Maybe we should do something like add an `--all` flag to include the disabled ones (and not include them by default)

**Comment by mraible** [comment]
Related: it'd be great to hide these apps that you can't do anything with from the CLI.

```
0oa1e98p21PmqqakA5d7	Okta Admin Console
0oa1e98p6rp9rDhCK5d7	Okta Dashboard
0oa1e98p7d1Goz4Wl5d7	Okta Browser Plugin
```
