### ISSUE TITLE
Feature Request - list all Applications and be able to create sample App

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/okta-cli#36]
Curious if you're interested at adding those 2 features

## List all applications

1. List first 20 or 50 or 100 applications (we can try to figure out what's best heuristic number together.) Or maybe the number can be parameter and default 20 and max is 1000.
2. Probably don't need to consider pagination now.

## Create sample application

Kind of similar to create real app, it'd be nice to allow create sample apps. 

```
e.g.
okta create-sample --app_id=xxxxx
> 1: React
> 2: Angular
> 3: Vue
```
The option varies depends what kind of application (dictated by the `app_id`)

What it does is
- check out our sample repo `gitHub.com/okta/samples-*` to a specific folder, e.g. `~/okta-samples`
- create env file
- start the sample app (optional as parameter like `--start` cause I'm not sure if we can just start native sample from cli.)

**Comment by bdemers** [comment]
We are actually working on something like this right now ;)

**Comment by bdemers** [comment]
`okta start` will create and configure apps based on samples, 
and `okta apps` will list all current applications in the org
(@haishengwu-okta please re-open this if this doesn't meet your needs)
