### ISSUE TITLE
Windows spring-boot run command should be "mvnw spring-boot:run" instead "./mvnw spring-boot:run"

### ISSUE THREAD

**Issue by KostiantynDrozd-okta** [okta/okta-cli#60]
When I created a spring-boot app with command `okta start`, I see message:
```
Run this application with:
    ./mvnw spring-boot:run
```
But command for windows to run looks like:
    
`mvnw spring-boot:run`

Do we need to change that message?

**Comment by bdemers** [comment]
Moved to: okta-samples/okta-spring-boot-sample#2

No a bad idea, just moving it to the correct repo
