### ISSUE TITLE
First name/Last name validation is missing.

### ISSUE THREAD

**Issue by KostiantynDrozd-okta** [okta/okta-cli#62]
First name/Last name validation is missing for command `command register`

Is it a good idea to add some validation for First and Last name during registration?
It was possible for me to create user first/last name using two or more words and special characters.

**Comment by bdemers** [comment]
It's possible (and not uncommon) for names to contain spaces.
"Billy Jo" could be a first name, hyphenated or other complex last names are also common.
I know people with:
* two first names
* two (or more) middle names
* a single letter for a first name
* multiple last names

Special characters _might_ be a different story, but given the complexities of names, IMHO it's best NOT to duplicate this validation and let the server-side handle it.

That said if you can trigger an error, based on invalid input and it's NOT handled correctly, please open a new issue. (i.e. the CLI should show a meaningful error with enough info for the user to try again with correct input)
