### ISSUE TITLE
Add Quarkus support

### ISSUE THREAD

**Issue by danielpetisme** [okta/okta-cli#70]
The objective is to provide a first class support for Quarkus application.

**Comment by mraible** [comment]
Related to https://github.com/okta/okta-cli/issues/29.

**Comment by mraible** [comment]
I believe this is fixed in 0.8.0 and can be closed.

**Comment by bdemers** [comment]
Yup shipped in [0.8.0](https://github.com/okta/okta-cli/releases/tag/okta-cli-tools-0.8.0)!

Thanks again @danielpetisme !!

**Comment by danielpetisme** [comment]
Thank you, you!!!
That's so cool
