### ISSUE TITLE
Add JHipster Quarkus support

### ISSUE THREAD

**Issue by danielpetisme** [okta/okta-cli#72]
The JHipster Quarkus blueprint has now an Okta support.
https://github.com/jhipster/generator-jhipster-quarkus/releases/tag/v0.2.0

It would be great to propose the same level of integration as Spring Jhipster

**Comment by bdemers** [comment]
Nice!!

Do we need anything in addition to what is here: https://github.com/okta/okta-cli/pull/71

Are the redirect URI's, scopes, etc needed all the same? Between JHipster's Spring and Quarkus integrations?

**Comment by danielpetisme** [comment]
IMHO, when #71 is merged.
Jhipster Quarkus can be made in couple of hours!

I need your help to fix the #71 CI, I'm stuck...

**Comment by danielpetisme** [comment]
In the context of Jhipster Quarkus the scopes and redirect uris are the same but the properties are different

**Comment by mraible** [comment]
Fixed in 0.8.0. https://github.com/okta/okta-cli/releases/tag/okta-cli-tools-0.8.0
