### ISSUE TITLE
Okta login does not trim org url

### ISSUE THREAD

**Issue by Giorgi** [okta/okta-cli#77]
When I copied org url from Okta dev console I accidentally copied an extra space character in front of the URL. Running `Okta login` didn't fail but running any command resulted in `Illegal character in scheme name` error.

**Comment by bdemers** [comment]
Thanks for the report @Giorgi!

**Comment by Gilgahex** [comment]
similarly it doesn't autofill the protocol

Iif you don't manually include `https://` at login in the string it fails 

This makes the UX bad, when you copy the URL from the web dashboard it does include the protocol & causes unnecessary friction 

![Screenshot_2022-06-30_17-28-54](https://user-images.githubusercontent.com/30332451/176799718-44ba6e05-7c24-4ea6-b390-92576aec9fe1.png)
